# Python NumPy Questions:

## Python NumPy (Array, Random, Math):

#### Write a Python program to print the NumPy version in your system.

### Write a Python program to reverse an array (first element becomes last).

In [10]:
import numpy as np
arr1=np.array(range(10))
print(arr1)
arr1=arr1[::-1]
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


### Write a Python program to convert a list and tuple into arrays.

In [19]:
lst=list(range(2,10,2))
tpl=tuple(range(10,20))
print('List is:', lst)
print('Tupple is:', tpl)
arr1=np.array(lst)
print('List into array: ',arr1)
arr2=np.array(tpl)
print('Tupple into array: ',arr2)

List is: [2, 4, 6, 8]
Tupple is: (10, 11, 12, 13, 14, 15, 16, 17, 18, 19)
List into array:  [2 4 6 8]
Tupple into array:  [10 11 12 13 14 15 16 17 18 19]


### Write a Python program to find common values between two arrays.

In [47]:
arr1=np.eye(5)
arr2=np.arange(0,5)
print(arr1)
print(arr2)
arr3=np.array(set(arr1.flatten()) & set(arr2))
print('Common values are: ', arr3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0 1 2 3 4]
Common values are:  {0.0, 1.0}


In [32]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

### Write a Python program compare two arrays using numpy.

In [55]:
arr1=np.arange(0,10)
arr2=np.arange(5,15)

print(arr1>arr2)

[False False False False False False False False False False]


### Write a Python program to change the dimension of an array.

In [63]:
arr1=np.array(range(1,50,5))
arr1.reshape(2,5)

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46]])

### Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.

In [89]:
arr1=np.array(range(3,100,3))
arr1
arr2=np.array(range(5,100,5))
arr2
set1=set(arr1) | set(arr2)
arr3=np.array(list(set1))
arr3
np.sum(arr3)

2318

### Write a Python program to convert a NumPy array into Python list structure.

In [90]:
arr1=np.arange(0,10)
list(arr1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### Write a Python program to how to add an extra column to a numpy array.

In [98]:
# NOT DONE
arr1=np.arange(0,24).reshape(4,6)
arr1
arr2=arr1.shape
arr2

(4, 6)

### Write a Python program to check whether the numpy array is empty or not.

In [100]:
# SEE
arr1=np.arange(0,10)
np.isnan(arr1)


array([False, False, False, False, False, False, False, False, False,
       False])