In [1]:
## numpy, pandas, matplotlib/seaborn

In [2]:
# installion of package
# !pip install <package_name>
!pip install numpy

# Numpy - Numerical Python 
import numpy as np

In [3]:
# len(dir(np))

In [4]:
## main datastructure in numpy package -> NDArray

In [5]:
### creating an array
arr = np.array(range(1,10))
print(type(arr))
print(arr)
arr

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

list properties
    - mutable
    - ordered/indexable
    - hetrogenous data
    - duplicate members allowed
    
    
array properties
    - ordered/indexable
    - duplicate members allowed
    - mutable
    - homogeous data

In [7]:
list_ = list(range(1,10))
print(list_)
arr = np.array(list_)
print(type(arr))
print(arr)
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
list_ = [1,2,1.4,'7']
print(list_)
arr = np.array(list_)
print(type(arr))
print(arr)
arr

# int-> float -> str

[1, 2, 1.4, '7']
<class 'numpy.ndarray'>
['1' '2' '1.4' '7']


array(['1', '2', '1.4', '7'], dtype='<U32')

In [9]:
list_ = [1,2,1.4]
print(list_)
arr = np.array(list_)
print(type(arr))
print(arr)
arr

# int-> float -> str

[1, 2, 1.4]
<class 'numpy.ndarray'>
[1.  2.  1.4]


array([1. , 2. , 1.4])

In [10]:
list_ = [1,2,1.4,'7',[1,2,3]]
print(list_)
arr = np.array(list_)
print(type(arr))
print(arr)
arr

# int-> float -> str

[1, 2, 1.4, '7', [1, 2, 3]]
<class 'numpy.ndarray'>
[1 2 1.4 '7' list([1, 2, 3])]


array([1, 2, 1.4, '7', list([1, 2, 3])], dtype=object)

# creating array objects

In [11]:
# using np.empty()
arr = np.empty(10) # 1D - array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([           nan, 0.0000000e+000, 1.3243022e-311, 2.0236929e-320,
       0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000])

In [12]:
# using np.empty()
arr = np.empty((5,2), dtype = int) # 2D -array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[1413566533, 1432108360],
       [1936876915, 1818575964],
       [1330380908, 1095516483],
       [1094996048, 1128087892],
       [1934974010, 1551069797]])

In [13]:
# using np.empty()
arr = np.empty((5,2,2)) # 3D -array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[[1.32429832e-311, 6.27463370e-322],
        [0.00000000e+000, 0.00000000e+000]],

       [[1.33511969e-306, 5.30276956e+180],
        [1.57076922e-076, 6.97801880e-076]],

       [[5.06793393e-086, 3.35708901e-143],
        [6.01433264e+175, 6.93885958e+218]],

       [[5.56218858e+180, 3.94356143e+180],
        [8.23036828e-067, 3.60501323e+175]],

       [[1.20743555e+161, 1.61964581e-051],
        [7.11889322e-144, 1.50008929e+248]]])

In [14]:
# using np.ones()
arr = np.ones(10, int) # 1D - array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
arr = np.ones((2,3)) # 1D - array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# using np.zeros()
arr = np.zeros(10) # 1D - array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# using np.zeros()
arr = np.zeros((5,2)) # 1D - array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
# using np.linspace()
arr = np.linspace(start = 1, stop = 3, num = 10) # 1D - array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [19]:
# using np.linspace()
arr = np.linspace(start = 1, stop = 3) # 1D - array   # start, stop, step, length => length = stop - start /step
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

In [20]:
# using np.arange()
arr = np.arange(10) # 1D - array  
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# using np.arange()
arr = np.arange(start = 5, stop = 50, step = 0.5) # 1D - array  
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. ,
       21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5,
       27. , 27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. ,
       32.5, 33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5,
       38. , 38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. ,
       43.5, 44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5,
       49. , 49.5])

In [22]:
# using np.random.xxx
for each in range(1,11):
    r_num = np.random.randint(2,7)
    print(r_num)

6
4
6
4
4
4
6
6
5
4


In [23]:
arr = np.random.randint(3,5, size = 9) #1D array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([4, 4, 4, 4, 4, 4, 4, 4, 4])

In [24]:
arr = np.random.randint(3,5, size = (2,3))
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[3, 4, 3],
       [4, 4, 3]])

In [25]:
arr = np.random.rand(5) #1D array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0.9791233 , 0.54010357, 0.2712509 , 0.26124037, 0.78277215])

In [26]:
arr = np.random.rand(5,3) #1D array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[0.80780581, 0.80369137, 0.15427045],
       [0.81471791, 0.65455699, 0.5250931 ],
       [0.65730452, 0.6166759 , 0.82750558],
       [0.09892517, 0.0514111 , 0.60841702],
       [0.49058176, 0.6049211 , 0.84759572]])

In [27]:
arr = np.random.randn(5) #1D array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 0.19708463, -1.13961511, -1.63299884,  0.19652555,  1.25433523])

In [28]:
# np.random.rand()

In [29]:
arr = np.random.randn(5,5) #1D array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[-2.21803083,  0.65933505, -1.09994558,  0.29092559, -1.25554357],
       [ 0.91476133,  0.48813382,  1.35638151, -1.62290613,  0.27817929],
       [-0.48833551,  0.63331672,  0.27896154,  0.85538958,  1.11339959],
       [ 1.34329876, -0.20263798,  0.98009928, -1.17029003, -0.18813662],
       [-1.8248726 , -0.56511461,  0.26738061, -0.1579234 , -0.83368827]])

In [30]:
## np.empty(), np.ones(), np.zeros(), np.linspace(), np.arange(), np.random.randint,rand,randn()

In [31]:
# np.array([[1,2,3],
# [1,2,4]])

In [32]:
# 
mylist =  list(range(1,11))
print(mylist)
# mylist + 2

# loop
# list comprehsion
# map

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [33]:
arr = np.array(mylist)
print(arr)
arr+2

[ 1  2  3  4  5  6  7  8  9 10]


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
# num_list = [1,2,3,4,5,'6']
# arr = np.array(num_list)
# arr*2

In [35]:
print(np.array(range(1,10))/2)
print(np.array(range(1,10))**2)
print(np.array(range(1,10))//2)
print(np.array(range(1,10))+2)
print(np.array(range(1,10))*2)

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 1  4  9 16 25 36 49 64 81]
[0 1 1 2 2 3 3 4 4]
[ 3  4  5  6  7  8  9 10 11]
[ 2  4  6  8 10 12 14 16 18]


In [36]:
# np.sum(), np.mean(), np.max(), np.min(), np.sort(),np.std(), np.rank(), np.sin(),np.consine(), np.dot(), np.log(), np.exmp()

In [37]:
arr1  = np.linspace(start = 0 , stop = 10, num = 10)
print(arr1)
arr2  = np.linspace(start = 11 , stop = 20, num = 10)
print(arr2)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [38]:
arr1 + arr2 

array([11.        , 13.11111111, 15.22222222, 17.33333333, 19.44444444,
       21.55555556, 23.66666667, 25.77777778, 27.88888889, 30.        ])

In [39]:
arr1 * arr2 

array([  0.        ,  13.33333333,  28.88888889,  46.66666667,
        66.66666667,  88.88888889, 113.33333333, 140.        ,
       168.88888889, 200.        ])

In [40]:
arr1 / arr2 

array([0.        , 0.09259259, 0.17094017, 0.23809524, 0.2962963 ,
       0.34722222, 0.39215686, 0.43209877, 0.46783626, 0.5       ])

In [41]:
arr1  = np.linspace(start = 0 , stop = 10, num = 10).reshape((5,2))
print(arr1)
arr2  = np.linspace(start = 11 , stop = 20, num = 10).reshape((5,2))
print(arr2)

[[ 0.          1.11111111]
 [ 2.22222222  3.33333333]
 [ 4.44444444  5.55555556]
 [ 6.66666667  7.77777778]
 [ 8.88888889 10.        ]]
[[11. 12.]
 [13. 14.]
 [15. 16.]
 [17. 18.]
 [19. 20.]]


In [42]:
arr1 + arr2

array([[11.        , 13.11111111],
       [15.22222222, 17.33333333],
       [19.44444444, 21.55555556],
       [23.66666667, 25.77777778],
       [27.88888889, 30.        ]])

In [43]:
arr1 * arr2

array([[  0.        ,  13.33333333],
       [ 28.88888889,  46.66666667],
       [ 66.66666667,  88.88888889],
       [113.33333333, 140.        ],
       [168.88888889, 200.        ]])

In [44]:
# np.dot(arr1,arr2) # np.dot is used for matrix multiple 

In [45]:
arr1  = np.linspace(start = 0 , stop = 10, num = 10).reshape((5,2))
print(arr1)
arr2  = np.linspace(start = 11 , stop = 20, num = 10).reshape((2,5))
print(arr2)

[[ 0.          1.11111111]
 [ 2.22222222  3.33333333]
 [ 4.44444444  5.55555556]
 [ 6.66666667  7.77777778]
 [ 8.88888889 10.        ]]
[[11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


In [49]:
arr1  = np.linspace(start = 0 , stop = 10, num = 10).reshape((5,2))
print(arr1)
arr2  = np.linspace(start = 11 , stop = 20, num = 10).reshape((2,5))
print(arr2)

[[ 0.          1.11111111]
 [ 2.22222222  3.33333333]
 [ 4.44444444  5.55555556]
 [ 6.66666667  7.77777778]
 [ 8.88888889 10.        ]]
[[11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


In [50]:
np.dot(arr1,arr2)

array([[ 17.77777778,  18.88888889,  20.        ,  21.11111111,
         22.22222222],
       [ 77.77777778,  83.33333333,  88.88888889,  94.44444444,
        100.        ],
       [137.77777778, 147.77777778, 157.77777778, 167.77777778,
        177.77777778],
       [197.77777778, 212.22222222, 226.66666667, 241.11111111,
        255.55555556],
       [257.77777778, 276.66666667, 295.55555556, 314.44444444,
        333.33333333]])

In [51]:
np.reshape(a = arr1, newshape = (1,10))

array([[ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
         5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ]])

In [52]:
arr1.reshape((1,10))

array([[ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
         5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ]])